
# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/xiaomi/maycorn-miuicamera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/maycorn-miuicamera/common

PRODUCT_PACKAGES += \
    MiuiCamera \
    libcamera_algoup_jni.xiaomi \
    libcamera_mianode_jni.xiaomi \
    libmicampostproc_client \
    vendor.xiaomi.hardware.campostproc@1.0 \
    libgui_shim_miuicamera.so
